name: Build & Deploy
on: [push, workflow_dispatch]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Get code
              uses: actions/checkout@v4
            - name: Install dep–µ
              run: npm ci
            - name: Build project
              run: npm run build
            - name: Upload Artifact
              uses: actions/upload-artifact@v4
              with:
                path: build # es pathum gtnvox filery savea anum git
                name: build-files
deploy: 
    needs: build
    runs-on: ubuntu-latest
    steps:
        - name: Get build project
          uses: actions/download-artifact@v4
          with:
            name: build-files